trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorVersion: '2'
  packageVersion: '0.$(Build.BuildNumber)'


steps:
- template: pipeline-steps/install-snk.yml

- template: pipeline-steps/restore_build_pack.yml

- template: pipeline-steps/run_all_tests.yml

- task: NuGetCommand@2
  displayName: "NuGet push GetcuReone source"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/FactFactory.$(packageVersion).nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'd5079c70-9bc4-4da1-b3c9-feb9869dfc91'
