trigger:
- release/*

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorVersion: '1'
  minorVersion: '0'
  pathVersion: '0'
  packageVersion: '$(majorVersion).$(minorVersion).$(pathVersion)'


steps:
- template: pipeline-steps/install-snk.yml

- template: pipeline-steps/restore_build_pack.yml

- template: pipeline-steps/run_all_tests.yml

- template: pipeline-steps/copy_nuget_to_artifacts.yml

# - task: NuGetCommand@2
#   displayName: "NuGet push nuget.org source"
#   inputs:
#     command: 'push'
#     packagesToPush: '$(Build.ArtifactStagingDirectory)/FactFactory*.nupkg'
#     nuGetFeedType: 'external'
#     publishFeedCredentials: 'Nuget.org'