trigger:
- release/*

pool:
  vmImage: 'windows-2019'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  nugetRepositoryFile: '$(Build.Repository.LocalPath)/FactFactory/NugetProject/bin/$(buildConfiguration)/FactFactory*.nupkg'


steps:
- task: NuGetToolInstaller@1
  displayName: 'NuGet tool installer'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(solution)'

- template: pipeline-steps/install-snk.yml

- task: VSBuild@1
  displayName: "VS build"
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: 'VS run tests'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*Tests*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testRunTitle: 'VS run tests'

- task: CopyFiles@2
  displayName: "Nuget copy to Artifacts folder"
  inputs:
    SourceFolder: '$(Build.Repository.LocalPath)/FactFactory/NugetProject/bin/$(buildConfiguration)'
    Contents: '*'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  displayName: "NuGet push GetcuReone source"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/FactFactory*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'd5079c70-9bc4-4da1-b3c9-feb9869dfc91'

- task: NuGetCommand@2
  displayName: "NuGet push nuget.org source"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'Nuget.org'