# Pipeline for dev branch current project
trigger:
  branches:
    include:
    - develop
    exclude:
    - release/*
    - master
pr:
  branches:
    include:
    - develop

resources:
  repositories:
    - repository: global_pipeline_template
      name: GetcuReone-Pipelines
      type: git

variables:
- group: global-variables-group
- group: GetcuReone-FactFactory-variables-group
- name: 'buildConfiguration'
  value: 'debug'
- name: 'majorVersion'
  value: $[variables['Dev_Major']]
- name: 'minorVersion'
  value: $[variables['Dev_Minor']]
- name: 'patchVersion'
  value: $[counter(format('{0}.{1}', variables.majorVersion, variables.minorVersion), 0)]
- ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
  - name: 'buildName'
    value: $[format('{0}-{1}.{2}.{3}', variables['Build.DefinitionName'], variables['majorVersion'], variables['minorVersion'], variables['patchVersion'])]
- ${{ if not(eq(variables['Build.SourceBranchName'], 'develop')) }}:
  - name: 'sourceBranchName'
    value: $[replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '')]
  - name: 'buildName'
    value: $[format('{0}-{1}-{2}.{3}.{4}', variables['sourceBranchName'], variables['Build.DefinitionName'], variables['majorVersion'], variables['minorVersion'], variables['patchVersion'])]

name: $[variables.buildName]

jobs:
  - template: nuget/develop_nuget_build_template.yml@global_pipeline_template
